<?php
add_action( 'acf/include_fields', function () {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key'                   => 'group_66f17c34c585e',
		'title'                 => 'Alingsas Hero',
		'fields'                => array(
			array(
				'key'               => 'field_66f17f106d799',
				'label'             => 'Image',
				'name'              => 'a_hero_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'uploader'          => '',
				'return_format'     => 'array',
				'acfe_thumbnail'    => 0,
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'preview_size'      => 'medium',
				'library'           => 'all',
			),
			array(
				'key'               => 'field_66f17c58932ab',
				'label'             => 'Search placeholder',
				'name'              => 'a_hero_search_placeholder',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'                           => 'field_66f27a0c23cf3',
				'label'                         => 'Quick links',
				'name'                          => 'quick_links',
				'aria-label'                    => '',
				'type'                          => 'repeater',
				'instructions'                  => '',
				'required'                      => 0,
				'conditional_logic'             => 0,
				'wrapper'                       => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'acfe_repeater_stylised_button' => 0,
				'layout'                        => 'table',
				'pagination'                    => 0,
				'min'                           => 0,
				'max'                           => 0,
				'collapsed'                     => '',
				'button_label'                  => 'Add link',
				'rows_per_page'                 => 20,
				'sub_fields'                    => array(
					array(
						'key'               => 'field_66f27a1c23cf4',
						'label'             => 'Button',
						'name'              => 'link',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'parent_repeater'   => 'field_66f27a0c23cf3',
					),
					array(
						'key'               => 'field_66f283611fe19',
						'label'             => 'Button color',
						'name'              => 'color',
						'aria-label'        => '',
						'type'              => 'radio',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'default'   => 'Default',
							'primary'   => 'Primary',
							'secondary' => 'Secondary',
						),
						'default_value'     => 'primary',
						'return_format'     => 'value',
						'allow_null'        => 0,
						'other_choice'      => 0,
						'layout'            => 'horizontal',
						'save_other_choice' => 0,
						'parent_repeater'   => 'field_66f27a0c23cf3',
					),
					array(
						'key'               => 'field_66f2845a1fe1a',
						'label'             => 'Filled / Outlined',
						'name'              => 'style',
						'aria-label'        => '',
						'type'              => 'radio',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'filled'   => 'Filled',
							'outlined' => 'Outlined',
						),
						'default_value'     => 'filled',
						'return_format'     => 'value',
						'allow_null'        => 0,
						'other_choice'      => 0,
						'layout'            => 'horizontal',
						'save_other_choice' => 0,
						'parent_repeater'   => 'field_66f27a0c23cf3',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'mod-alingsashero',
				),
			),
			array(
				array(
					'param'    => 'block',
					'operator' => '==',
					'value'    => 'acf/alingsashero',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'acfe_display_title'    => '',
		'acfe_autosync'         => array(
			0 => 'json',
		),
		'acfe_form'             => 0,
		'acfe_meta'             => '',
		'acfe_note'             => '',
	) );
} );

