<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_66f17c34c585e',
    'title' => __('Hero', 'modularity-alingsashero'),
    'fields' => array(
        0 => array(
            'key' => 'field_66f17c3e932aa',
            'label' => __('Title', 'modularity-alingsashero'),
            'name' => 'a_hero_text',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 1,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        1 => array(
            'key' => 'field_66f17f106d799',
            'label' => __('Image', 'modularity-alingsashero'),
            'name' => 'a_hero_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'uploader' => '',
            'return_format' => 'array',
            'library' => 'all',
            'acfe_thumbnail' => 0,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 1,
            'preview_size' => 'medium',
        ),
        2 => array(
            'key' => 'field_66f17c58932ab',
            'label' => __('Search placeholder', 'modularity-alingsashero'),
            'name' => 'a_hero_search_placeholder',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 1,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        3 => array(
            'key' => 'field_66f27a0c23cf3',
            'label' => __('Quick links', 'modularity-alingsashero'),
            'name' => 'quick_links',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add button', 'modularity-alingsashero'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_66f27a1c23cf4',
                    'label' => __('Button', 'modularity-alingsashero'),
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'allow_in_bindings' => 1,
                    'parent_repeater' => 'field_66f27a0c23cf3',
                ),
                1 => array(
                    'key' => 'field_66f283611fe19',
                    'label' => __('Button color', 'modularity-alingsashero'),
                    'name' => 'color',
                    'aria-label' => '',
                    'type' => 'radio',
                    'instructions' => __('Attention and Outlined cannot be used together due to contrast issues', 'modularity-alingsashero'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'attention' => __('Attention', 'modularity-alingsashero'),
                        'primary' => __('Primary', 'modularity-alingsashero'),
                        'secondary' => __('Secondary', 'modularity-alingsashero'),
                    ),
                    'default_value' => __('primary', 'modularity-alingsashero'),
                    'return_format' => 'value',
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'allow_in_bindings' => 1,
                    'layout' => 'horizontal',
                    'save_other_choice' => 0,
                    'parent_repeater' => 'field_66f27a0c23cf3',
                ),
                2 => array(
                    'key' => 'field_66f2845a1fe1a',
                    'label' => __('Filled / Outlined', 'modularity-alingsashero'),
                    'name' => 'style',
                    'aria-label' => '',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'filled' => __('Filled', 'modularity-alingsashero'),
                        'outlined' => __('Outlined', 'modularity-alingsashero'),
                    ),
                    'default_value' => __('filled', 'modularity-alingsashero'),
                    'return_format' => 'value',
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'allow_in_bindings' => 1,
                    'layout' => 'horizontal',
                    'save_other_choice' => 0,
                    'parent_repeater' => 'field_66f27a0c23cf3',
                ),
            ),
        ),
        4 => array(
            'key' => 'field_676423ea37683',
            'label' => __('Show search?', 'modularity-alingsashero'),
            'name' => 'show_search',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'allow_in_bindings' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_67c8a1b2rek01',
            'label' => __('Antal Rek AI-rekommendationer', 'modularity-alingsashero'),
            'name' => 'number_of_recommendations',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => __('Antal rekommendationsknappar från Rek AI (0 = av).', 'modularity-alingsashero'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'min' => 0,
            'max' => 7,
            'step' => 1,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        6 => array(
            'key' => 'field_67c8a1b2rek02',
            'label' => __('Exkludera sidor', 'modularity-alingsashero'),
            'name' => 'excludetree',
            'aria-label' => '',
            'type' => 'post_object',
            'instructions' => __('Sidor som ska exkluderas från Rek AI-rekommendationer.', 'modularity-alingsashero'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => '',
            'post_status' => '',
            'taxonomy' => '',
            'return_format' => 'object',
            'multiple' => 1,
            'allow_null' => 0,
            'bidirectional' => 0,
            'ui' => 1,
            'bidirectional_target' => array(
            ),
            'save_custom' => 0,
            'save_post_type' => '',
            'save_post_status' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-alingsashero',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/alingsashero',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}